[package]
name = "compute_canister"
version = "0.3.0"
edition = "2021"
build = "build.rs"

[lib]
crate-type = ["cdylib"]

[dependencies]
ic-cdk = "0.13"
ic-cdk-macros = "0.13"
candid = "0.10"
serde = { version = "1", features = ["derive"] }
sha2 = "0.10"
hex = "0.4"

[build-dependencies]
